// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package edit

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClipboard creates a new instance of MockClipboard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClipboard(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClipboard {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockClipboard{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockClipboard is an autogenerated mock type for the Clipboard type
type MockClipboard struct {
	mock.Mock
}

type MockClipboard_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClipboard) EXPECT() *MockClipboard_Expecter {
	return &MockClipboard_Expecter{mock: &_m.Mock}
}

// ReadText provides a mock function for the type MockClipboard
func (_mock *MockClipboard) ReadText(limit int) ([]byte, error) {
	ret := _mock.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for ReadText")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]byte, error)); ok {
		return returnFunc(limit)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []byte); ok {
		r0 = returnFunc(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClipboard_ReadText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadText'
type MockClipboard_ReadText_Call struct {
	*mock.Call
}

// ReadText is a helper method to define mock.On call
//   - limit int
func (_e *MockClipboard_Expecter) ReadText(limit any) *MockClipboard_ReadText_Call {
	return &MockClipboard_ReadText_Call{Call: _e.mock.On("ReadText", limit)}
}

func (_c *MockClipboard_ReadText_Call) Run(run func(limit int)) *MockClipboard_ReadText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClipboard_ReadText_Call) Return(bytes []byte, err error) *MockClipboard_ReadText_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockClipboard_ReadText_Call) RunAndReturn(run func(limit int) ([]byte, error)) *MockClipboard_ReadText_Call {
	_c.Call.Return(run)
	return _c
}

// WriteText provides a mock function for the type MockClipboard
func (_mock *MockClipboard) WriteText(bytes []byte) error {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for WriteText")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClipboard_WriteText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteText'
type MockClipboard_WriteText_Call struct {
	*mock.Call
}

// WriteText is a helper method to define mock.On call
//   - bytes []byte
func (_e *MockClipboard_Expecter) WriteText(bytes any) *MockClipboard_WriteText_Call {
	return &MockClipboard_WriteText_Call{Call: _e.mock.On("WriteText", bytes)}
}

func (_c *MockClipboard_WriteText_Call) Run(run func(bytes []byte)) *MockClipboard_WriteText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClipboard_WriteText_Call) Return(err error) *MockClipboard_WriteText_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClipboard_WriteText_Call) RunAndReturn(run func(bytes []byte) error) *MockClipboard_WriteText_Call {
	_c.Call.Return(run)
	return _c
}
