// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package edit

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIME creates a new instance of MockIME. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIME(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIME {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockIME{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockIME is an autogenerated mock type for the IME type
type MockIME struct {
	mock.Mock
}

type MockIME_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIME) EXPECT() *MockIME_Expecter {
	return &MockIME_Expecter{mock: &_m.Mock}
}

// ContentType provides a mock function for the type MockIME
func (_mock *MockIME) ContentType(password bool, multiline bool) {
	_mock.Called(password, multiline)
	return
}

// MockIME_ContentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContentType'
type MockIME_ContentType_Call struct {
	*mock.Call
}

// ContentType is a helper method to define mock.On call
//   - password bool
//   - multiline bool
func (_e *MockIME_Expecter) ContentType(password any, multiline any) *MockIME_ContentType_Call {
	return &MockIME_ContentType_Call{Call: _e.mock.On("ContentType", password, multiline)}
}

func (_c *MockIME_ContentType_Call) Run(run func(password bool, multiline bool)) *MockIME_ContentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIME_ContentType_Call) Return() *MockIME_ContentType_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIME_ContentType_Call) RunAndReturn(run func(password bool, multiline bool)) *MockIME_ContentType_Call {
	_c.Run(run)
	return _c
}

// CursorRect provides a mock function for the type MockIME
func (_mock *MockIME) CursorRect(x float64, y float64, w float64, h float64) {
	_mock.Called(x, y, w, h)
	return
}

// MockIME_CursorRect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CursorRect'
type MockIME_CursorRect_Call struct {
	*mock.Call
}

// CursorRect is a helper method to define mock.On call
//   - x float64
//   - y float64
//   - w float64
//   - h float64
func (_e *MockIME_Expecter) CursorRect(x any, y any, w any, h any) *MockIME_CursorRect_Call {
	return &MockIME_CursorRect_Call{Call: _e.mock.On("CursorRect", x, y, w, h)}
}

func (_c *MockIME_CursorRect_Call) Run(run func(x float64, y float64, w float64, h float64)) *MockIME_CursorRect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIME_CursorRect_Call) Return() *MockIME_CursorRect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIME_CursorRect_Call) RunAndReturn(run func(x float64, y float64, w float64, h float64)) *MockIME_CursorRect_Call {
	_c.Run(run)
	return _c
}

// Disable provides a mock function for the type MockIME
func (_mock *MockIME) Disable() {
	_mock.Called()
	return
}

// MockIME_Disable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disable'
type MockIME_Disable_Call struct {
	*mock.Call
}

// Disable is a helper method to define mock.On call
func (_e *MockIME_Expecter) Disable() *MockIME_Disable_Call {
	return &MockIME_Disable_Call{Call: _e.mock.On("Disable")}
}

func (_c *MockIME_Disable_Call) Run(run func()) *MockIME_Disable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIME_Disable_Call) Return() *MockIME_Disable_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIME_Disable_Call) RunAndReturn(run func()) *MockIME_Disable_Call {
	_c.Run(run)
	return _c
}

// Enable provides a mock function for the type MockIME
func (_mock *MockIME) Enable() {
	_mock.Called()
	return
}

// MockIME_Enable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enable'
type MockIME_Enable_Call struct {
	*mock.Call
}

// Enable is a helper method to define mock.On call
func (_e *MockIME_Expecter) Enable() *MockIME_Enable_Call {
	return &MockIME_Enable_Call{Call: _e.mock.On("Enable")}
}

func (_c *MockIME_Enable_Call) Run(run func()) *MockIME_Enable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIME_Enable_Call) Return() *MockIME_Enable_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIME_Enable_Call) RunAndReturn(run func()) *MockIME_Enable_Call {
	_c.Run(run)
	return _c
}

// Surrounding provides a mock function for the type MockIME
func (_mock *MockIME) Surrounding(text string, cursor int, anchor int) {
	_mock.Called(text, cursor, anchor)
	return
}

// MockIME_Surrounding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Surrounding'
type MockIME_Surrounding_Call struct {
	*mock.Call
}

// Surrounding is a helper method to define mock.On call
//   - text string
//   - cursor int
//   - anchor int
func (_e *MockIME_Expecter) Surrounding(text any, cursor any, anchor any) *MockIME_Surrounding_Call {
	return &MockIME_Surrounding_Call{Call: _e.mock.On("Surrounding", text, cursor, anchor)}
}

func (_c *MockIME_Surrounding_Call) Run(run func(text string, cursor int, anchor int)) *MockIME_Surrounding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIME_Surrounding_Call) Return() *MockIME_Surrounding_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIME_Surrounding_Call) RunAndReturn(run func(text string, cursor int, anchor int)) *MockIME_Surrounding_Call {
	_c.Run(run)
	return _c
}
